[package]
name = "postflop-solver-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "postflop_solver"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
postflop-solver = { path = "..", features = ["bincode", "rayon"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
