"""Animate cfreach and CFV as 13x13 poker range charts across iterations.

Usage:
    python scripts/animate_range_chart.py data/bt1/KcQh7s.bt1 [boundary_idx]

Requires: data/bt1/<board>_hands.json (generated by dump_hands example)
"""

import json
import struct
import sys
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from matplotlib.colors import Normalize
from pathlib import Path


# 13x13 range chart: row/col 0=A, 1=K, ..., 12=2
RANK_LABELS = ["A", "K", "Q", "J", "T", "9", "8", "7", "6", "5", "4", "3", "2"]


def hand_to_grid(c1, c2):
    """Map a hand (c1, c2) to (row, col) in 13x13 range chart.

    Upper triangle (row < col) = suited
    Diagonal (row == col) = pairs
    Lower triangle (row > col) = offsuit
    """
    rank1 = c1 >> 2
    rank2 = c2 >> 2
    suit1 = c1 & 3
    suit2 = c2 & 3

    # Invert: encoded rank 0=2..12=A → grid 0=A..12=2
    g1 = 12 - rank1
    g2 = 12 - rank2

    if rank1 == rank2:
        # Pair → diagonal
        return (g1, g1)
    elif suit1 == suit2:
        # Suited → upper triangle (row < col)
        return (min(g1, g2), max(g1, g2))
    else:
        # Offsuit → lower triangle (row > col)
        return (max(g1, g2), min(g1, g2))


def cell_label(r, c):
    """Human-readable label for a range chart cell."""
    if r == c:
        return f"{RANK_LABELS[r]}{RANK_LABELS[c]}"
    elif r < c:
        return f"{RANK_LABELS[r]}{RANK_LABELS[c]}s"
    else:
        return f"{RANK_LABELS[c]}{RANK_LABELS[r]}o"


def load_hands(json_path):
    """Load hand mappings from dump_hands output."""
    with open(json_path) as f:
        return json.load(f)


def load_bt1_boundary(path, target_boundary=0):
    """Load a single boundary from .bt1 file."""
    with open(path, "rb") as f:
        f.read(8)  # magic
        f.read(4)  # version
        num_oop = struct.unpack("<I", f.read(4))[0]
        num_ip = struct.unpack("<I", f.read(4))[0]
        num_boundaries = struct.unpack("<I", f.read(4))[0]
        num_iterations = struct.unpack("<I", f.read(4))[0]
        starting_pot = struct.unpack("<f", f.read(4))[0]

        per_boundary_bytes = (num_oop + num_ip + num_ip + num_oop) * 4

        cfreach_ip_all = np.zeros((num_iterations, num_ip), dtype=np.float32)
        cfreach_oop_all = np.zeros((num_iterations, num_oop), dtype=np.float32)
        cfv_oop_all = np.zeros((num_iterations, num_oop), dtype=np.float32)
        cfv_ip_all = np.zeros((num_iterations, num_ip), dtype=np.float32)
        exploitabilities = np.zeros(num_iterations, dtype=np.float32)

        for t in range(num_iterations):
            f.read(4)
            exploitabilities[t] = struct.unpack("<f", f.read(4))[0]
            f.read(4)

            f.read(per_boundary_bytes * target_boundary)

            cfv_oop_all[t] = np.frombuffer(f.read(num_oop * 4), dtype=np.float32)
            cfreach_ip_all[t] = np.frombuffer(f.read(num_ip * 4), dtype=np.float32)
            cfv_ip_all[t] = np.frombuffer(f.read(num_ip * 4), dtype=np.float32)
            cfreach_oop_all[t] = np.frombuffer(f.read(num_oop * 4), dtype=np.float32)

            f.read(per_boundary_bytes * (num_boundaries - target_boundary - 1))

    return {
        "num_oop": num_oop, "num_ip": num_ip,
        "num_iterations": num_iterations, "starting_pot": starting_pot,
        "boundary_idx": target_boundary,
        "cfreach_ip": cfreach_ip_all, "cfreach_oop": cfreach_oop_all,
        "cfv_oop": cfv_oop_all, "cfv_ip": cfv_ip_all,
        "exploitabilities": exploitabilities,
    }


def build_grid_mapping(hands_list):
    """Build mapping from hand index to (row, col) in 13x13 grid.

    Returns:
        grid_map: list of (row, col) per hand index
        cell_hands: dict (row, col) → list of hand indices
    """
    grid_map = []
    cell_hands = {}
    for i, hand in enumerate(hands_list):
        c1, c2 = hand[0], hand[1]
        r, c = hand_to_grid(c1, c2)
        grid_map.append((r, c))
        cell_hands.setdefault((r, c), []).append(i)
    return grid_map, cell_hands


def hands_to_grid(values, cell_hands):
    """Average per-hand values into 13x13 grid cells."""
    grid = np.full((13, 13), np.nan)
    for (r, c), indices in cell_hands.items():
        grid[r, c] = np.mean([values[i] for i in indices])
    return grid


def animate(data, hands_data, output_path, board_name):
    n = data["num_iterations"]
    pot = data["starting_pot"]

    # Build grid mappings for both players
    _, cell_oop = build_grid_mapping(hands_data["oop"])
    _, cell_ip = build_grid_mapping(hands_data["ip"])

    # Precompute grids for all iterations
    cfreach_oop_grids = []
    cfreach_ip_grids = []
    cfv_oop_grids = []
    cfv_ip_grids = []

    for t in range(n):
        cfreach_oop_grids.append(hands_to_grid(data["cfreach_oop"][t], cell_oop))
        cfreach_ip_grids.append(hands_to_grid(data["cfreach_ip"][t], cell_ip))
        cfv_oop_grids.append(hands_to_grid(data["cfv_oop"][t], cell_oop))
        cfv_ip_grids.append(hands_to_grid(data["cfv_ip"][t], cell_ip))

    # Global color ranges
    cr_vmax = max(
        max(np.nanmax(g) for g in cfreach_oop_grids),
        max(np.nanmax(g) for g in cfreach_ip_grids),
    )
    cfv_abs_max = max(
        max(np.nanmax(np.abs(g[~np.isnan(g)])) for g in cfv_oop_grids),
        max(np.nanmax(np.abs(g[~np.isnan(g)])) for g in cfv_ip_grids),
    )

    fig, axes = plt.subplots(2, 2, figsize=(16, 14))
    (ax_cr_oop, ax_cr_ip) = axes[0]
    (ax_cfv_oop, ax_cfv_ip) = axes[1]

    # Masked array for NaN cells (blocked by board cards)
    def masked(grid):
        return np.ma.masked_where(np.isnan(grid), grid)

    # Initial plots
    cmap_reach = plt.cm.Blues.copy()
    cmap_reach.set_bad("lightgray")
    cmap_cfv = plt.cm.RdBu_r.copy()
    cmap_cfv.set_bad("lightgray")

    im_cr_oop = ax_cr_oop.imshow(masked(cfreach_oop_grids[0]), cmap=cmap_reach,
                                  vmin=0, vmax=cr_vmax, aspect="equal")
    im_cr_ip = ax_cr_ip.imshow(masked(cfreach_ip_grids[0]), cmap=cmap_reach,
                                vmin=0, vmax=cr_vmax, aspect="equal")
    im_cfv_oop = ax_cfv_oop.imshow(masked(cfv_oop_grids[0]), cmap=cmap_cfv,
                                    vmin=-cfv_abs_max, vmax=cfv_abs_max, aspect="equal")
    im_cfv_ip = ax_cfv_ip.imshow(masked(cfv_ip_grids[0]), cmap=cmap_cfv,
                                  vmin=-cfv_abs_max, vmax=cfv_abs_max, aspect="equal")

    plt.colorbar(im_cr_oop, ax=ax_cr_oop, fraction=0.046, label="reach")
    plt.colorbar(im_cr_ip, ax=ax_cr_ip, fraction=0.046, label="reach")
    plt.colorbar(im_cfv_oop, ax=ax_cfv_oop, fraction=0.046, label="cfv")
    plt.colorbar(im_cfv_ip, ax=ax_cfv_ip, fraction=0.046, label="cfv")

    # Add cell labels
    texts = {}
    for ax_key, ax in [("cr_oop", ax_cr_oop), ("cr_ip", ax_cr_ip),
                        ("cfv_oop", ax_cfv_oop), ("cfv_ip", ax_cfv_ip)]:
        texts[ax_key] = []
        for r in range(13):
            row_texts = []
            for c in range(13):
                txt = ax.text(c, r, cell_label(r, c), ha="center", va="center",
                              fontsize=5.5, color="black", fontweight="bold")
                row_texts.append(txt)
            texts[ax_key].append(row_texts)

    for ax in [ax_cr_oop, ax_cr_ip, ax_cfv_oop, ax_cfv_ip]:
        ax.set_xticks(range(13))
        ax.set_yticks(range(13))
        ax.set_xticklabels(RANK_LABELS, fontsize=7)
        ax.set_yticklabels(RANK_LABELS, fontsize=7)

    ax_cr_oop.set_title(f"OOP cfreach ({data['num_oop']} hands)")
    ax_cr_ip.set_title(f"IP cfreach ({data['num_ip']} hands)")
    ax_cfv_oop.set_title(f"OOP CFV ({data['num_oop']} hands)")
    ax_cfv_ip.set_title(f"IP CFV ({data['num_ip']} hands)")

    fig.suptitle("", fontsize=14)
    plt.tight_layout(rect=[0, 0, 1, 0.95])

    def update(frame):
        t = frame
        exploit_pct = data["exploitabilities"][t] / pot * 100

        fig.suptitle(
            f"{board_name} — Boundary {data['boundary_idx']} — "
            f"Iteration {t}/{n-1}  |  Exploitability: {exploit_pct:.2f}%",
            fontsize=13, fontweight="bold",
        )

        im_cr_oop.set_data(masked(cfreach_oop_grids[t]))
        im_cr_ip.set_data(masked(cfreach_ip_grids[t]))
        im_cfv_oop.set_data(masked(cfv_oop_grids[t]))
        im_cfv_ip.set_data(masked(cfv_ip_grids[t]))

        return im_cr_oop, im_cr_ip, im_cfv_oop, im_cfv_ip

    anim = FuncAnimation(fig, update, frames=n, interval=120, blit=False)
    anim.save(output_path, writer="pillow", fps=10)
    print(f"Saved: {output_path}")
    plt.close()


def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/animate_range_chart.py <file.bt1> [boundary_idx]")
        sys.exit(1)

    bt1_path = sys.argv[1]
    boundary = int(sys.argv[2]) if len(sys.argv) > 2 else 0
    board = Path(bt1_path).stem

    # Load hand mappings
    hands_path = Path(bt1_path).parent / f"{board}_hands.json"
    if not hands_path.exists():
        print(f"Error: {hands_path} not found.")
        print(f"Run: cargo run --example dump_hands --release --features \"bincode rayon\" -- config/{board}.json")
        sys.exit(1)

    hands_data = load_hands(hands_path)
    data = load_bt1_boundary(bt1_path, boundary)

    out_path = f"data/out/range_chart_{board}_b{boundary}.gif"
    Path("data/out").mkdir(parents=True, exist_ok=True)

    print(f"Board: {board}, Boundary: {boundary}")
    print(f"OOP: {data['num_oop']} hands, IP: {data['num_ip']} hands, Iters: {data['num_iterations']}")
    print("Generating range chart animation...")

    animate(data, hands_data, out_path, board)


if __name__ == "__main__":
    main()
