#!/usr/bin/env python3
"""
DeepStack-style bucketed value network trainer.

Reads training data generated by `generate_raw_data` → `project_data`, trains an MLP with
zero-sum correction, and exports to ONNX.

Usage:
    python train.py \
        --input-dir ./data/training_data \
        --output turn_model.onnx \
        --epochs 300 \
        --batch-size 512 \
        --lr 0.001

Input:  inputs.npy  shape [N, 2015]  = board(15) + range_oop(1000) + range_ip(1000)
Output: targets.npy shape [N, 2000]  = cfv_oop(1000) + cfv_ip(1000)
"""

import argparse
import os
import glob
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

K = 1000
BOARD_FEATURES = 15
INPUT_DIM = BOARD_FEATURES + 2 * K   # 2015
OUTPUT_DIM = 2 * K                    # 2000


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------

class ZeroSumCorrectionLayer(nn.Module):
    """Enforce zero-sum property at the aggregate level.

    After the raw MLP output, compute the game value error and distribute
    half of it to each player's CFVs (weighted by range probabilities).

    Zero-sum constraint:
        sum(range_oop * cfv_oop) + sum(range_ip * cfv_ip) = 0
    """

    def forward(self, raw_output, range_oop, range_ip):
        """
        raw_output: [B, 2000] — raw network predictions
        range_oop:  [B, 1000] — OOP range probabilities
        range_ip:   [B, 1000] — IP range probabilities
        """
        cfv_oop = raw_output[:, :K]
        cfv_ip = raw_output[:, K:]

        # Compute game value: should be 0 if zero-sum holds
        game_value = (
            (range_oop * cfv_oop).sum(dim=1, keepdim=True)
            + (range_ip * cfv_ip).sum(dim=1, keepdim=True)
        )

        # Correction: subtract half the error from each player
        correction = game_value / 2.0

        # Avoid division by zero for range sums
        oop_total = range_oop.sum(dim=1, keepdim=True).clamp(min=1e-8)
        ip_total = range_ip.sum(dim=1, keepdim=True).clamp(min=1e-8)

        cfv_oop_corrected = cfv_oop - correction / oop_total
        cfv_ip_corrected = cfv_ip - correction / ip_total

        return torch.cat([cfv_oop_corrected, cfv_ip_corrected], dim=1)


class TurnValueNetwork(nn.Module):
    """MLP for predicting bucketed CFVs from game state.

    Architecture: 7 hidden layers × 500 neurons, PReLU activations.
    Final layer: zero-sum correction.
    """

    def __init__(self, hidden_dim=500, num_layers=7):
        super().__init__()

        layers = []
        in_dim = INPUT_DIM
        for _ in range(num_layers):
            layers.append(nn.Linear(in_dim, hidden_dim))
            layers.append(nn.PReLU())
            in_dim = hidden_dim
        layers.append(nn.Linear(hidden_dim, OUTPUT_DIM))

        self.backbone = nn.Sequential(*layers)
        self.zero_sum = ZeroSumCorrectionLayer()

    def forward(self, x):
        """
        x: [B, 2015] — board(15) + range_oop(1000) + range_ip(1000)
        Returns: [B, 2000] — cfv_oop(1000) + cfv_ip(1000)
        """
        raw = self.backbone(x)

        # Extract ranges from input for zero-sum correction
        range_oop = x[:, BOARD_FEATURES : BOARD_FEATURES + K]
        range_ip = x[:, BOARD_FEATURES + K :]

        return self.zero_sum(raw, range_oop, range_ip)


# ---------------------------------------------------------------------------
# Loss
# ---------------------------------------------------------------------------

class ReachWeightedHuberLoss(nn.Module):
    """Reach-weighted Huber loss on pot-normalized CFVs.

    Weights each hand's CFV error by the opponent's reach probability
    for that bucket, so high-probability scenarios dominate the loss.
    """

    def __init__(self, delta=1.0):
        super().__init__()
        self.huber = nn.HuberLoss(reduction="none", delta=delta)

    def forward(self, pred, target, range_oop, range_ip):
        """
        pred:      [B, 2000]
        target:    [B, 2000]
        range_oop: [B, 1000] — weights for IP's CFV (opponent's reach)
        range_ip:  [B, 1000] — weights for OOP's CFV (opponent's reach)
        """
        loss_per_bucket = self.huber(pred, target)

        # OOP CFVs weighted by IP range (opponent's reach)
        # IP CFVs weighted by OOP range (opponent's reach)
        weights = torch.cat([range_ip, range_oop], dim=1)

        # Normalize weights per sample
        weight_sum = weights.sum(dim=1, keepdim=True).clamp(min=1e-8)
        weights_norm = weights / weight_sum

        return (loss_per_bucket * weights_norm).sum(dim=1).mean()


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_data(input_dir):
    """Load all .npy chunks from input_dir, concatenate."""
    input_files = sorted(glob.glob(os.path.join(input_dir, "inputs*.npy")))
    target_files = sorted(glob.glob(os.path.join(input_dir, "targets*.npy")))

    if not input_files:
        # Try single file
        inp = os.path.join(input_dir, "inputs.npy")
        tgt = os.path.join(input_dir, "targets.npy")
        if os.path.exists(inp):
            input_files = [inp]
            target_files = [tgt]
        else:
            raise FileNotFoundError(f"No inputs*.npy found in {input_dir}")

    inputs = np.concatenate([np.load(f) for f in input_files], axis=0)
    targets = np.concatenate([np.load(f) for f in target_files], axis=0)

    assert inputs.shape[1] == INPUT_DIM, f"Expected {INPUT_DIM} input dims, got {inputs.shape[1]}"
    assert targets.shape[1] == OUTPUT_DIM, f"Expected {OUTPUT_DIM} output dims, got {targets.shape[1]}"
    assert inputs.shape[0] == targets.shape[0], "Input/target sample count mismatch"

    print(f"Loaded {inputs.shape[0]} samples from {len(input_files)} file(s)")
    return inputs, targets


# ---------------------------------------------------------------------------
# Train/val split by unique board
# ---------------------------------------------------------------------------

BOARD_GEOM_FEATURES = 12  # indices 0-11 are board geometry (card-only)


def board_grouped_split(inputs, val_fraction=0.1, seed=42):
    """Split samples by unique board geometry to prevent data leakage.

    All samples sharing the same board (flop+turn) go entirely into
    the training set OR entirely into the validation set.

    Features 0-11 encode board geometry (ranks, suits, structure).
    Features 12-14 encode pot/stack and are ignored for grouping.

    Returns (train_indices, val_indices) as numpy arrays.
    """
    n = inputs.shape[0]

    # Round board features to avoid float comparison issues
    # (values come from integer divisions, so 4 decimals is plenty)
    board_keys = np.round(inputs[:, :BOARD_GEOM_FEATURES], decimals=4)

    # Map each sample to a board ID
    board_to_id = {}
    sample_board_ids = np.empty(n, dtype=np.int64)
    for i in range(n):
        key = tuple(board_keys[i])
        if key not in board_to_id:
            board_to_id[key] = len(board_to_id)
        sample_board_ids[i] = board_to_id[key]

    n_boards = len(board_to_id)

    # Count samples per board
    board_counts = np.bincount(sample_board_ids, minlength=n_boards)

    # Need at least 2 unique boards for a meaningful split
    if n_boards < 2:
        print(
            f"WARNING: Only {n_boards} unique board(s). "
            "Falling back to random sample split (board grouping impossible)."
        )
        perm = np.random.RandomState(seed).permutation(n)
        val_size = max(1, int(n * val_fraction))
        val_idx = perm[:val_size]
        train_idx = perm[val_size:]
        print(
            f"Board-grouped split: {n_boards} unique boards | "
            f"train={len(train_idx)} samples | "
            f"val={len(val_idx)} samples (RANDOM FALLBACK)"
        )
        return train_idx, val_idx

    # Shuffle boards and split
    rng = np.random.RandomState(seed)
    board_perm = rng.permutation(n_boards)

    # Walk through shuffled boards, assigning to val until we reach target size.
    # Always reserve at least 1 board for training.
    val_board_set = set()
    val_sample_count = 0
    target_val = max(1, int(n * val_fraction))

    for bid in board_perm:
        if val_sample_count >= target_val:
            break
        # Don't assign the last board to val — keep at least 1 for training
        if len(val_board_set) >= n_boards - 1:
            break
        val_board_set.add(bid)
        val_sample_count += board_counts[bid]

    # Build index arrays
    val_mask = np.isin(sample_board_ids, list(val_board_set))
    val_idx = np.where(val_mask)[0]
    train_idx = np.where(~val_mask)[0]

    # Verify no board leakage
    train_boards = set(sample_board_ids[train_idx])
    val_boards = set(sample_board_ids[val_idx])
    assert train_boards.isdisjoint(val_boards), "Board leakage detected!"

    print(
        f"Board-grouped split: {n_boards} unique boards | "
        f"train={len(train_idx)} samples ({len(train_boards)} boards) | "
        f"val={len(val_idx)} samples ({len(val_boards)} boards)"
    )

    return train_idx, val_idx


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def train(args):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    # Load data
    inputs, targets = load_data(args.input_dir)
    n = inputs.shape[0]

    # Train/val split by UNIQUE BOARD (prevents board leakage)
    #
    # Board-geometry features are indices 0-11 (ranks, suits, structural).
    # Features 12-14 are pot/stack and vary across samples for the same board.
    # Two samples sharing the same board geometry must go into the same split,
    # otherwise the model memorizes board patterns instead of learning poker.
    train_idx, val_idx = board_grouped_split(inputs, val_fraction=0.1, seed=42)

    train_inputs = torch.tensor(inputs[train_idx], dtype=torch.float32)
    train_targets = torch.tensor(targets[train_idx], dtype=torch.float32)
    val_inputs = torch.tensor(inputs[val_idx], dtype=torch.float32)
    val_targets = torch.tensor(targets[val_idx], dtype=torch.float32)

    train_loader = DataLoader(
        TensorDataset(train_inputs, train_targets),
        batch_size=args.batch_size,
        shuffle=True,
        drop_last=True,
    )
    val_loader = DataLoader(
        TensorDataset(val_inputs, val_targets),
        batch_size=args.batch_size,
        shuffle=False,
    )

    # Model
    model = TurnValueNetwork(
        hidden_dim=args.hidden_dim,
        num_layers=args.num_layers,
    ).to(device)

    num_params = sum(p.numel() for p in model.parameters())
    print(f"Model: {args.num_layers} layers × {args.hidden_dim} neurons, {num_params:,} params")

    # Optimizer + scheduler
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=1e-5)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.epochs, eta_min=args.lr * 0.1
    )

    criterion = ReachWeightedHuberLoss(delta=args.huber_delta)

    best_val_loss = float("inf")
    best_state = None

    for epoch in range(args.epochs):
        # Train
        model.train()
        train_loss = 0.0
        train_batches = 0

        for batch_x, batch_y in train_loader:
            batch_x = batch_x.to(device)
            batch_y = batch_y.to(device)

            range_oop = batch_x[:, BOARD_FEATURES : BOARD_FEATURES + K]
            range_ip = batch_x[:, BOARD_FEATURES + K :]

            pred = model(batch_x)
            loss = criterion(pred, batch_y, range_oop, range_ip)

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            train_loss += loss.item()
            train_batches += 1

        scheduler.step()

        # Validate
        model.eval()
        val_loss = 0.0
        val_batches = 0

        with torch.no_grad():
            for batch_x, batch_y in val_loader:
                batch_x = batch_x.to(device)
                batch_y = batch_y.to(device)

                range_oop = batch_x[:, BOARD_FEATURES : BOARD_FEATURES + K]
                range_ip = batch_x[:, BOARD_FEATURES + K :]

                pred = model(batch_x)
                loss = criterion(pred, batch_y, range_oop, range_ip)

                val_loss += loss.item()
                val_batches += 1

        avg_train = train_loss / max(train_batches, 1)
        avg_val = val_loss / max(val_batches, 1)
        lr = scheduler.get_last_lr()[0]

        if (epoch + 1) % 10 == 0 or epoch == 0:
            print(
                f"Epoch {epoch + 1:4d}/{args.epochs} | "
                f"train={avg_train:.6f} val={avg_val:.6f} | "
                f"lr={lr:.6f}"
            )

        if avg_val < best_val_loss:
            best_val_loss = avg_val
            best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}

    # Restore best model
    if best_state is not None:
        model.load_state_dict(best_state)
        print(f"\nBest val loss: {best_val_loss:.6f}")

    # Export to ONNX
    export_onnx(model, args.output, device)


# ---------------------------------------------------------------------------
# ONNX export
# ---------------------------------------------------------------------------

def export_onnx(model, output_path, device):
    """Export model to ONNX with dynamic batch axis."""
    model.eval()
    model.to(device)

    dummy_input = torch.randn(1, INPUT_DIM, device=device)

    torch.onnx.export(
        model,
        dummy_input,
        output_path,
        input_names=["input"],
        output_names=["output"],
        dynamic_axes={
            "input": {0: "batch_size"},
            "output": {0: "batch_size"},
        },
        opset_version=17,
        dynamo=False,  # single .onnx file (no external .onnx.data)
    )

    file_size = os.path.getsize(output_path) / (1024 * 1024)
    print(f"Exported to {output_path} ({file_size:.1f} MB)")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Train bucketed value network")
    parser.add_argument(
        "--input-dir",
        required=True,
        help="Directory containing inputs.npy and targets.npy",
    )
    parser.add_argument(
        "--output",
        default="turn_model.onnx",
        help="Output ONNX model path (default: turn_model.onnx)",
    )
    parser.add_argument("--epochs", type=int, default=300)
    parser.add_argument("--batch-size", type=int, default=512)
    parser.add_argument("--lr", type=float, default=0.001)
    parser.add_argument("--hidden-dim", type=int, default=500)
    parser.add_argument("--num-layers", type=int, default=7)
    parser.add_argument("--huber-delta", type=float, default=1.0)

    args = parser.parse_args()
    train(args)


if __name__ == "__main__":
    main()
